version: '3.9'
services:
  mongo-server:
    image: mongo:4.4
    container_name: mongo-server
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongodb_network
  mongo-client:
    image: mongo-express:latest
    container_name: mongo-client
    restart: always
    depends_on:
      - mongo-server
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-server
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_DATABASE=AuthService
    ports:
      - "8082:8082"
    networks:
      - mongodb_network
volumes:
  mongodb_data:
networks:
  mongodb_network:
